name: HA Status Bot
version: "1.0.1"
slug: ha_status_bot
description: Bot de Telegram para consultar luces, sensores, puertas, baterías y temperaturas de Home Assistant
url: "https://github.com/joaquinhegi/ha-status-bot"

arch:
  - aarch64
  - amd64

startup: services
boot: auto
init: false

homeassistant_api: true

options:
  telegram_token: ""
  allowed_chat_ids: ""
  low_battery_threshold: 20

schema:
  telegram_token: password
  allowed_chat_ids: str
  low_battery_threshold: int